---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "marketplace.fullname" . }}
  labels:
    {{- include "marketplace.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "marketplace.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: pocketbase
  labels:
    {{- include "marketplace.labels" . | nindent 4 }}
spec:
  type: {{ .Values.dbservice.type }}
  ports:
    - port: {{ .Values.dbservice.port }}
      targetPort: db-http
      protocol: TCP
      name: db-port
  selector:
    {{- include "db.selectorLabels" . | nindent 4 }}
